Public Module GlobalConstants


    'MACHINEFOLDERSSECURITY
    Public Const MACHINE_FOLDERS_SECURITY_ON As String = "ON"
    Public Const MACHINE_FOLDERS_SECURITY_OFF As String = "OFF"

    'VERBOSITYLOGLEVEL
    Public Const VERBOSITYLOGLEVEL_DEBUG As String = "DEBUG"
    Public Const VERBOSITYLOGLEVEL_INFO As String = "INFO"
    Public Const VERBOSITYLOGLEVEL_WARNING As String = "WARNING"
    Public Const VERBOSITYLOGLEVEL_ERROR As String = "ERROR"

    'NOME MACCHINE
    Public Const MACHINENAME_MECCANOPLASTICA1 As String = "MECCANOPLASTICA1"
    Public Const MACHINENAME_MECCANOPLASTICA4 As String = "MECCANOPLASTICA4"
    Public Const MACHINENAME_DUETTI As String = "DUETTI"
    Public Const MACHINENAME_DUETTI2 As String = "DUETTI2"
    Public Const MACHINENAME_AXOMATIC As String = "AXOMATIC"
    Public Const MACHINENAME_ETICH As String = "ETICH"
    Public Const MACHINENAME_LAY As String = "LAY"
    Public Const MACHINENAME_PICKER23017 As String = "PICKER23017"
    Public Const MACHINENAME_PICKER23018 As String = "PICKER23018"
    Public Const MACHINENAME_PRONTOWASH1 As String = "PRONTOWASH1"
    Public Const MACHINENAME_PRONTOWASH2 As String = "PRONTOWASH2"

    'LOTTO
    Public Const LOTTO_NONAPPLICATO As String = "NONAPPLICATO"

End Module
